{{- if .Values.api.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.api.oidc.admins | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-viewer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.api.oidc.viewers | nindent 4 }}
{{- end }}
